version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    container_name: server_php_env
    links:
      - db
    ports:
      - '8089:80'
  db:
    image: mysql:8.0.16
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3309:3306
    container_name: DB_mysql_env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
volumes:
  mysql-db: