version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    restart: always
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    links:
      - db
    ports:
      - '8089:80'
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
